### ISSUE TITLE
Git conflict messages in flex2sms_schema.sql

### ISSUE THREAD

**Issue by evanmsanders** [evanmsanders/flex2sms#107]
Re-create schema file from current db please. Obviously, we haven't used this in a while. Still has conflicts from the original merge of the authentication branch, meaning it can't be used to create the db.

**Comment by mazzone** [comment]
@evanmsanders to test if new SQL is acceptable.

**Comment by mazzone** [comment]
Closing this as the new schema looks OK, but it's also going to change again when we migrate to gammu.
